name = "auto-resume-worker"
main = "./worker.ts"
compatibility_date = "2025-02-27"

[[r2_buckets]]
binding = "RESUME_STORAGE"
bucket_name = "auto-bucket"
preview_bucket_name= "auto-bucket-preview"

[build]
pages_build_output_dir = "/dist"